# Generated by Django 5.0.3 on 2024-03-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_tag_rename_source_code_project_source_code_link_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
    ]
